[pytest]
testpaths = tier1 tier2 tier3 tier4
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore::requests.RequestsDependencyWarning
    ignore::DeprecationWarning
pythonpath = .
